### ISSUE TITLE
Hard-coded paths in ResonanceAudioReverbBakingWindow.cs

### ISSUE THREAD

**Issue by andybak** [resonance-audio/resonance-audio#10]
Line 80/81:

    private const string materialMapperAssetPath =
    "Assets/3rdParty/ResonanceAudio/Resources/ResonanceAudioMaterialMapper.asset";

This obviously breaks if Resonance is moved to a subdirectory. Surely there's a better way to handle this? I'm rather keen on keeping 3rd Party assets separate from my project's assets.

**Comment by anokta** [comment]
Good point! The issue should be fixed now via 2fbf9c3.

Replaced the absolute path by a relative one, so moving the ResonanceAudio asset directory should not be an issue anymore - as long as the name (and the content) of the folder is intact.
