### ISSUE TITLE
which headers do I need when using from C?

### ISSUE THREAD

**Issue by Neurrone** [resonance-audio/resonance-audio#12]
Hi,

I've successfully compiled on Windows 10 with VS2017, but only see 2 headers in the install/includes folder. That can't be it, since for e.g the web audio bindings have many classes and methods to represent the various nodes. 

Which other files do I need to use it from C?

**Comment by Neurrone** [comment]
Looking at it more closely, the classes exposed in the install/include folder are actually from the graph folder.

Is there any documentation or a hello world example to play a source from c/c++? 

Also, comments in the sources aren't Doxygen-style, so I was also wondering what tool is used to generate html documentation.

**Comment by jkammerl** [comment]
The public C++ API interfaces can be found [in the API folder](https://github.com/resonance-audio/resonance-audio/tree/master/resonance_audio/api). Resonance Audio spatializes raw audio buffers and contains wrappers/plugins for various game/audio engines.  It does *not* contain an audio engine  which would be required to provide a "hello world sample that plays an audio source file".

**Comment by cuiyange** [comment]
@Neurrone 

Hello, I'm sorry to bother you.

My project is using the C++API of resonance audio.  I use resonance_audio_api.h now , but I don't seem to know the function of the interface. Like you, I can't find the  hello world example to play a source from c/c++. I'm eager to know how the interface works. If you already know, please help me. 

Thank you very much!

**Comment by Neurrone** [comment]
@cuiyange I'm no longer using this.
