### ISSUE TITLE
clone_core_deps.sh seems out-of-date?

### ISSUE THREAD

**Issue by Sinnerboy89** [resonance-audio/resonance-audio#37]
When using said script to clone Eigen and pffft libraries, it seems to be trying to use Mercurial to grab non-existent repos (Eigen for example, has moved over to GitLab). I get http authorisation prompts and 403s or aborts when trying the script, seemingly because of this.

Workaround was to replace mercurial commands with git clone commands, pointing to correct repo URLs - but wanted to check if there was any other reason this wasn't updated?

**Comment by anokta** [comment]
That seems correct, thanks for reporting this!

Linked pull request should hopefully resolve the issue.
