### ISSUE TITLE
Does pffft have a license?

### ISSUE THREAD

**Issue by chrisfromwork** [resonance-audio/resonance-audio#48]
I am trying to understand what dependency license exists for this project. It does not seem that the bitbucket link to pffft contains a license file. Does anyone know what license pffft uses?

**Comment by anokta** [comment]
Hi,

The license is embedded in their source code directly, e.g., you can see it in the header: https://bitbucket.org/jpommier/pffft/src/master/pffft.h#lines-1:46

**Comment by chrisfromwork** [comment]
thanks! @anokta
