### ISSUE TITLE
VST2_SDK install does not contain pluginterfaces/vst2.x/aeffect.h

### ISSUE THREAD

**Issue by chrisfromwork** [resonance-audio/resonance-audio#49]
It looks like the vst sdk install called out in the project readme is missing aeffect.h and aeffectx.h files expected by cmake. Does anyone know where to obtain these headers?

**Comment by chrisfromwork** [comment]
looks like this may be a dupe of https://github.com/resonance-audio/resonance-audio/issues/39

**Comment by anokta** [comment]
Yup, seems like the same issue, replied on the other thread, closing this.
