### ISSUE TITLE
Head coordinate convention is not documented.

### ISSUE THREAD

**Issue by Ono-Sendai** [resonance-audio/resonance-audio#51]
It's not documented (that I could find at least) which direction corresponds to up, forwards, right etc.. for the head model.

After some reverse engineering I have determined that Resonance follows the OpenGL convention of x = right, y = up, and -z = forwards.

As this is a matter of convention, it should be documented.

**Comment by anokta** [comment]
that's right, the world space uses the right-handed coordinate system. it is actually documented here (and below throughout the related functionality): https://github.com/resonance-audio/resonance-audio/blob/1f68420412cdde70fa3c66d73b8fb5d8c065c8d3/resonance_audio/base/misc_math.h#L82
