### ISSUE TITLE
unable to compile unity plugin with android toolchain in windows

### ISSUE THREAD

**Issue by ghost** [resonance-audio/resonance-audio#7]
Dear all,

I would like to compile the resonance audio plugin for unity in Windows, with also the android support (which should be located in ResonanceAudio/Plugins/Android/libs/armeabi-v7a/libaudiopluginresonanceaudio.so) but unfortunatly having problems.

This is my configuration: Windows 10 + gitBash + mercurial + cmake3.11
After having cloned and built core dependencies and unity dependencies, I am able to compile correcly the unity plugin ( ./build.sh -t=UNITY_PLUGIN ), but when I try ./build.sh -t=UNITY_PLUGIN --android_toolchain , I get this error:

CMake Error at third_party/android-cmake/android.toolchain.cmake:616 (message):
  Could not find any working toolchain in the NDK.  Probably your Android NDK
  is broken.
Call Stack (most recent call first):
  C:/Program Files (x86)/cmake-3.11.0-win64-x64/share/cmake-3.11/Modules/CMakeDe                                                                                                                termineSystem.cmake:94 (include)
  CMakeLists.txt:39 (project)

CMake Error at CMakeLists.txt:39 (project):
  CMAKE_SYSTEM_NAME is 'Android' but CMAKE_GENERATOR specifies a platform
  too: 'Visual Studio 14 2015 Win64'

So, I modified the build.sh in this way (line 29):
from -> ANDROID_NDK="~/android-ndk-r15c/"
to -> ANDROID_NDK="./android-ndk-r15c/"
then tried again to compile and got this error:

CMake Deprecation Warning at C:/Program Files (x86)/cmake-3.11.0-win64-x64/share/cmake-3.11/Modules/CMakeForceCompiler.cmake:69 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  third_party/android-cmake/android.toolchain.cmake:1128 (CMAKE_FORCE_C_COMPILER)
  C:/Program Files (x86)/cmake-3.11.0-win64-x64/share/cmake-3.11/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:39 (project)

CMake Deprecation Warning at C:/Program Files (x86)/cmake-3.11.0-win64-x64/share/cmake-3.11/Modules/CMakeForceCompiler.cmake:83 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  third_party/android-cmake/android.toolchain.cmake:1140 (CMAKE_FORCE_CXX_COMPILER)
  C:/Program Files (x86)/cmake-3.11.0-win64-x64/share/cmake-3.11/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:39 (project)

CMake Error at CMakeLists.txt:39 (project):
  CMAKE_SYSTEM_NAME is 'Android' but CMAKE_GENERATOR specifies a platform
  too: 'Visual Studio 14 2015 Win64'

What am I missing ?

Maybe could be of some interest the workaround I used for Windows 10 to get a working android plugin of resonance-audio for unity. I write it down here.

Open a Windows PowerShell window as Admnistrator, and execute this line:
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
in order to enable the Linux subsystem.
Then go to Microsoft Store, search for a linux distribution (I opted for Ubuntu) and install it.

Lunch the distribution, locate the resonance-audio-master folder and type following commands:

sudo apt update
sudo apt-get install cmake
sudo apt-get install gcc
sudo apt-get install g++
sudo apt-get install mercurial
sudo apt-get install git
sudo apt-get install p7zip-full
wget "https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip"
7z x android-ndk-r15c-linux-x86_64.zip
./third_party/clone_core_deps.sh
./third_party/clone_build_install_unity_deps.sh

Open in an editor the file build.sh located in the root folder of the project, and modify the line 29:
from -> ANDROID_NDK="~/android-ndk-r15c/"
to -> ANDROID_NDK="./android-ndk-r15c/"

Then go back to the command line and type:
./build.sh -t=UNITY_PLUGIN --android_toolchain 

The generated resonance-audio plugin for unity will not work on Windows ( and in fact in the folder ResonanceAudio/Plugins/x86_64 there is not the audiopluginresonanceaudio.dll ), but the ResonanceAudio/Plugins/Android/libs/armeabi-v7a/libaudiopluginresonanceaudio.so has been correctly generated and it works on android devices.
So you just need to copy the folder ResonanceAudio/Plugins/Android and paste it in the resonance-audio-unity-plugin compiled in Windows (where you have a working audiopluginresonanceaudio.dll but not the libaudiopluginresonanceaudio.so)

It would be great to have a Windows version of resonance-audio unity plugin with android support without having to compile it twice. Could someone help?

I add this information: when I made the cross-compiling from Windows through the linux subsystem it was much faster than the compiling for Windows (from Windows, through git bash). So, the cross compiling for Windows, from the linux subsystem of Windows itself, could be, maybe, an interesting solution.

Thanks and regards,
Paino

**Comment by jkammerl** [comment]
The error message you are getting indicates that the Android NDK cannot be found at the given path. Could you please double check that the ANDROID_NDK path is set correctly in your build.sh file. Try setting it to an absolute path and avoid spaces in your folder names. I hope this helps.

**Comment by ghost** [comment]
Check folders name, no spaces, then tried your suggestion but did not work.
I placed the android-ndk-r15c folder in the main folder of resonance-audio-master. Is it correct? Or should be in third_party or somewhere else?

Maybe I am missing also this instruction (taken from https://github.com/taka-no-me/android-cmake) : 
cmake -DCMAKE_TOOLCHAIN_FILE=android.toolchain.cmake -DANDROID_NDK=<ndk_path> -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="armeabi-v7a with NEON" <source_path> && cmake --build .

I do not understand what should be the <source_path>.

**Comment by jkammerl** [comment]
You are correct,  it doesn't matter where the android-ndk-r15c folder lives as long as the ANDROID_NDK environment variable points to it. 
It's a good idea to test the android-cmake tool separately. <source_path> should be the root folder of the repository.

**Comment by gooderist** [comment]
I am also unable to build from Windows using --android_toolchain using ndk r20

My warnings look like this...
```CMake Warning at third_party/android-cmake/android.toolchain.cmake:323 (message):
  Could not determine machine name for compiler from
  C:/code/android-ndk-r20/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64
Call Stack (most recent call first):
  third_party/android-cmake/android.toolchain.cmake:550 (__DETECT_TOOLCHAIN_MACHINE_NAME)
  third_party/android-cmake/android.toolchain.cmake:607 (__GLOB_NDK_TOOLCHAINS)
  C:/Program Files/CMake/share/cmake-3.12/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:39 (project)```
