### ISSUE TITLE
libaudiopluginresonanceaudio

### ISSUE THREAD

**Issue by Acousticslab** [resonance-audio/resonance-audio#8]
Dear all,
I have compiled resonance audio with UNITY_PLUGIN target and android_toolchain option.

In the path: ResonanceAudio\Plugins\Android\libs\armeabi-v7a
the created .so is 8350 KB , the original one download from here (https://github.com/resonance-audio/resonance-audio-unity-sdk/tree/master/Assets/ResonanceAudio/Plugins/Android/libs/armeabi-v7a) is only 450 KB.

When I build my unity app with the original version the audio is spatialized and works well.
Instead If I build the unity app with my own compiled version, audio lags.

Could someone explain how to recompile obtaining the same result as the resonance-audio-unity-sdk ?

Thanks and regards

**Comment by anokta** [comment]
Hmm, the difference in file size seems to be quite large! I didn't have a chance to test it myself, but some initial thoughts on this - in case it helps:

- Did you make sure with cflags and all that you're building an optimized release library, i.e., non-debug stripped .so?
- Also regarding cflags, presuming audio lags do come from cpu starvation, could you check if you include such options to make sure SIMD optimizations are enabled, e.g., something along the lines of "-mfloat-abi=softfp -mfpu=neon -O3" (see [here](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html) for reference)?

**Comment by Acousticslab** [comment]
Thanks for reply, seen it just few minutes after having posted a specific issue, sorry.
After many attempts, I can say that audio is slowed down and stuttered (but still correctly spatialized) only using Oculus SDK, to target Gear VR or Oculus GO. With the cardboard SDK audio instead everything works well with the recompiled version. Cannot say if it is a CPU problem or wrong buffering or other causes...
Could you please tell where these cflags are ? Again sorry.

**Comment by tristanjl** [comment]
Also seeing a very similar set of issues when manually building the ios fmod plugin vs downloading the pre-built version via github. The prebuilt version is also a static lib, whereas, by default, the output of running "build.sh -t=FMOD_PLUGIN --ios_os_toolchain" is a dylib. So there is clearly something that differs in the behaviour of build.sh compared with the build process for the pre-built version that is available on github.

I've modified the relevant CMakeLists.txt locally to ensure a static library is output and have tried a number of optimization settings for each of the dependent libs, but have not yet been able to figure out the source of the stuttering.

**Comment by tristanjl** [comment]
I appear to have isolated the problem. DCHECK from logging.h is not compiling away as appears to be expected. There is also no compile flag with which to enable/disable DCHECK. With a very simple test, I had over 60% CPU usage going to ChannelView::operator[], and redefining DCHECK resolved this issue.

**Comment by jkammerl** [comment]
If you see a high computational load from DCHECK, this is a strong indicator that you don't compile in optimized mode. Make sure you add the --profile=Release argument to the build script.
