### ISSUE TITLE
Slowed and stuttered audio with Oculus SDK

### ISSUE THREAD

**Issue by Acousticslab** [resonance-audio/resonance-audio#9]
Dear all,
I successfully recompiled the resonance audio Unity plugin with android toolchain (in Linux environment).
I developed a VR app with the ResonanceAudioSoundfield prefab, for decoding an Ambisonics audio track (1st order, 4 channels).

Here the problem: if I use the cardboard SDK in unity, everything works well, audio is fluid and correctly spatialized, but instead if I use the Oculus SDK (I would like to target Samsung Gear VR or Oculus GO) the audio is corrupted. I can still perceive the correct spatialization, but audio is really slowed down and stuttering. 

It seems a buffering problem...

Is there any way to solve?

**Comment by jkammerl** [comment]
Slowed down and stuttering audio is a strong indicator for not having enough CPU resources which is not necessarily an audio issue. The cardboard SDK is heavily optimized for mobile applications. I recommend using Unity's CPU monitor to identify what components take up most of your CPU.
